import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { extname, join } from "node:path";
import { brand, dim, fg, green, muted, red } from "./color.js";

// ── Tool discovery ──────────────────────────────────────────────────

const SKIP_DIRS = new Set(["node_modules", ".git", "dist", "build", "coverage"]);
// Common method/keyword names that match the shape but aren't agent tools.
const SKIP_NAMES = new Set([
  "execute",
  "default",
  "constructor",
  "handler",
  "then",
  "catch",
  "finally",
  "call",
  "apply",
]);

function isSourceFile(name: string): boolean {
  if (name.endsWith(".d.ts")) return false;
  if (name.endsWith(".test.ts") || name.endsWith(".test.js")) return false;
  if (name.endsWith(".spec.ts") || name.endsWith(".spec.js")) return false;
  const ext = extname(name);
  return ext === ".ts" || ext === ".js" || ext === ".mjs" || ext === ".cjs";
}

export function collectSourceFiles(dir: string): string[] {
  const files: string[] = [];
  const walk = (d: string) => {
    let entries: string[];
    try {
      entries = readdirSync(d);
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = join(d, entry);
      let st;
      try {
        st = statSync(full);
      } catch {
        continue;
      }
      if (st.isDirectory()) {
        if (!SKIP_DIRS.has(entry)) walk(full);
      } else if (isSourceFile(entry)) {
        files.push(full);
      }
    }
  };
  walk(dir);
  return files;
}

export function extractToolNames(source: string): string[] {
  const names = new Set<string>();

  // `toolName: async (` or `toolName: async function(`
  for (const m of source.matchAll(/(\w+)\s*:\s*async\s*(?:function\s*)?\(/g)) {
    names.add(m[1]!);
  }
  // `export async function toolName`
  for (const m of source.matchAll(/export\s+async\s+function\s+(\w+)/g)) {
    names.add(m[1]!);
  }
  // `name: "toolName"` near `type: "function"` (either ordering, within 120 chars)
  for (const m of source.matchAll(
    /name\s*:\s*["'](\w+)["'][\s\S]{0,120}?type\s*:\s*["']function["']/g,
  )) {
    names.add(m[1]!);
  }
  for (const m of source.matchAll(
    /type\s*:\s*["']function["'][\s\S]{0,120}?name\s*:\s*["'](\w+)["']/g,
  )) {
    names.add(m[1]!);
  }

  return [...names].filter((n) => !SKIP_NAMES.has(n));
}

// ── Heuristics → YAML ───────────────────────────────────────────────

type Category =
  | "destructive"
  | "notify"
  | "shell"
  | "deploy"
  | "mutate"
  | "readonly"
  | "unknown";

function categorize(name: string): Category {
  const n = name.toLowerCase();
  if (/(delete|remove|drop|destroy|purge)/.test(n)) return "destructive";
  if (/(send|email|notify|publish)/.test(n)) return "notify";
  if (/(run|exec|command|shell)/.test(n)) return "shell";
  if (/(push|deploy|release)/.test(n)) return "deploy";
  if (/(create|update|write|modify)/.test(n)) return "mutate";
  if (/(read|get|fetch|list|search)/.test(n)) return "readonly";
  return "unknown";
}

/** Render a commented YAML spec for the discovered tools. */
export function generateSpecYaml(names: string[]): string {
  const lines: string[] = [];
  lines.push("# Generated by `agentmint scan` — review and edit before use.");
  lines.push("# Heuristics are conservative starting points, not final rules.");
  lines.push('version: "1.0"');

  if (names.length > 0) {
    lines.push("tools:");
    for (const name of names) {
      const cat = categorize(name);
      lines.push(`  ${name}:`);
      switch (cat) {
        case "destructive":
          lines.push("    # destructive action — blocked by default");
          lines.push("    action: block");
          break;
        case "shell":
          lines.push("    # shell/exec — block obviously destructive commands");
          lines.push("    input:");
          lines.push("      properties:");
          lines.push("        command:");
          lines.push("          blocked_patterns:");
          lines.push('            - "rm -rf"');
          lines.push('            - "mkfs"');
          lines.push('            - ":(){ :|:& };:"');
          lines.push("          action: block");
          break;
        case "deploy":
          lines.push("    # deploy/push — block protected targets");
          lines.push("    input:");
          lines.push("      properties:");
          lines.push("        branch:");
          lines.push("          blocked_values:");
          lines.push('            - "main"');
          lines.push('            - "master"');
          lines.push("          action: block");
          break;
        case "notify":
          lines.push("    # outbound message — suggest a read/lookup prerequisite:");
          lines.push("    # requires:");
          lines.push("    #   - lookup_recipient");
          break;
        case "mutate":
          lines.push("    # mutation — suggest reading before writing:");
          lines.push("    # requires:");
          lines.push("    #   - read_target");
          break;
        case "readonly":
          lines.push("    # read-only — no rules needed");
          break;
        default:
          lines.push("    # no heuristic matched — add rules as needed");
          break;
      }
    }
  }

  // Always include sane default breakers.
  lines.push("breakers:");
  lines.push("  loop:");
  lines.push("    max_identical_calls: 5");
  lines.push("  velocity:");
  lines.push("    max_calls_per_window: 15");
  lines.push("    window_seconds: 30");

  return lines.join("\n") + "\n";
}

// ── CLI ─────────────────────────────────────────────────────────────

function parseArgs(argv: string[]): { dir?: string; out?: string; help: boolean } {
  let dir: string | undefined;
  let out: string | undefined;
  let help = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--dir") dir = argv[++i];
    else if (a === "--out") out = argv[++i];
    else if (a === "--help" || a === "-h") help = true;
  }
  return { dir, out, help };
}

function showHelp(): void {
  console.log("");
  console.log(`  ${brand()}  ${dim("scan")}`);
  console.log(`  ${muted("Auto-generate a starter spec from your tool source")}`);
  console.log("");
  console.log(`  ${fg("Usage:")}  agentmint scan --dir ${dim("<path>")} [--out ${dim("<path>")}]`);
  console.log("");
  console.log(`  ${fg("Options:")}`);
  console.log(`    ${fg("--dir")}   ${muted("Directory to scan for .ts/.js tool definitions (required)")}`);
  console.log(`    ${fg("--out")}   ${muted("Write the spec to a file (default: stdout)")}`);
  console.log("");
  console.log(`  ${fg("Examples:")}`);
  console.log(`    ${dim("$")} agentmint scan --dir ./src`);
  console.log(`    ${dim("$")} agentmint scan --dir ./src --out agentmint.spec.yaml`);
  console.log("");
}

export function scanDir(dir: string): string {
  const files = collectSourceFiles(dir);
  const names = new Set<string>();
  for (const file of files) {
    try {
      for (const n of extractToolNames(readFileSync(file, "utf-8"))) names.add(n);
    } catch {
      // Unreadable file — skip.
    }
  }
  return generateSpecYaml([...names].sort());
}

export async function runScan(): Promise<void> {
  const { dir, out, help } = parseArgs(process.argv.slice(3));

  if (help || !dir) {
    showHelp();
    if (!dir && !help) process.exitCode = 1;
    return;
  }

  try {
    statSync(dir);
  } catch {
    console.error("");
    console.error(`  ${red("✗")} Could not read directory ${red(dir)}`);
    console.error("");
    process.exitCode = 1;
    return;
  }

  const yaml = scanDir(dir);

  if (out) {
    writeFileSync(out, yaml, "utf-8");
    console.error(`  ${green("✓")} Wrote spec to ${fg(out)}`);
  } else {
    process.stdout.write(yaml);
  }
}
